---
# tasks file for jenkins_role

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

    # Install Jenkins
- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: http://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Update apt cache for Jenkins
  apt:
    update_cache: yes
    
- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
