apiVersion: v1
kind: Pod
metadata:
  name: pod-with-red-toleration
spec:
  tolerations:
  - key: "color"
    operator: "Equal"
    value: "red"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

