apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivolve-app
  namespace: mohamedyousry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivolve-app
  template:
    metadata:
      labels:
        app: ivolve-app
    spec:
      containers:
      - name: ivolve-app
        image: engyousry/ivolve-app:v1
        ports:
        - containerPort: 8090

