apiVersion: v1
kind: Service
metadata:
  name: ivolve-app-service
  namespace: mohamedyousry
spec:
  selector:
    app: ivolve-app
    
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      
  type: NodePort    
