apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-instance
  namespace: mohamedyousry
spec:
  server:
    route:
      enabled: true
  dex:
    image: quay.io/dexidp/dex:v2.27.0
    openShiftOAuth: true
  rbac:
    policy: |
      g, system:cluster-admins, role:admin
