apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: mohamedyousry
spec:
  selector:
    app: python-app
    
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      
  type: NodePort    
